# ./pre-commit-config.yaml
---
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v24.5.0
    hooks:
      - id: ansible-lint
        pass_filenames: true
        stages: [manual]
        additional_dependencies:
          - ansible-core<2.16
          - ansible

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: "docs/jekyll/ansible-docs/ansible-autodoc.md"
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=mdx]
        exclude: "docs/jekyll/ansible-docs/ansible-autodoc.md"
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-yaml
      - id: check-json
        exclude: "docs/cookiecutter_input.json"
      - id: check-toml
        exclude: "cliff.toml"
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-symlinks

  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: generate-docs
        name: Generate Documentation
        entry: make build-docs
        language: system
        always_run: true
        pass_filenames: false

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.3.3
    hooks:
      - id: cspell
        stages: [commit-msg]
        args: ["--config", "./cspell.json"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
