---
galaxy_info:
  author: "Jared Cook"
  description: "Install Discord flatpak."
  # company: "Optional Company Name"

  # Must use valid SPDX identifiers like 'GPL-3.0-or-later'
  license: "GPL-3.0-or-later"

  min_ansible_version: "2.10"

  # Galaxy/Automation Hub uses these to categorize your role
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Debian
      versions:
        - all
    - name: Ubuntu
        - all

  galaxy_tags:
    - flatpak
    - desktop
    - apps

dependencies: []
